<a href="https://colab.research.google.com/github/Muhammad-Musharraf/Machine-Learning/blob/main/Loan_Approved_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
df=pd.read_csv("/content/drive/MyDrive/loan_data.csv")

In [25]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [26]:
df.shape

(45000, 14)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [28]:
df.describe()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
count,45000.000000,4.500000e+04,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,27.764178,8.031905e+04,5.410333,9583.157556,11.006606,0.139725,5.867489,632.608756,0.222222
std,6.045108,8.042250e+04,6.063532,6314.886691,2.978808,0.087212,3.879702,50.435865,0.415744
min,20.000000,8.000000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,390.000000,0.000000
25%,24.000000,4.720400e+04,1.000000,5000.000000,8.590000,0.070000,3.000000,601.000000,0.000000
50%,26.000000,6.704800e+04,4.000000,8000.000000,11.010000,0.120000,4.000000,640.000000,0.000000
75%,30.000000,9.578925e+04,8.000000,12237.250000,12.990000,0.190000,8.000000,670.000000,0.000000
max,144.000000,7.200766e+06,125.000000,35000.000000,20.000000,0.660000,30.000000,850.000000,1.000000

In [29]:
df.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

In [32]:
# Remove Unnesssary Colums
df=df.drop(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership'],axis=1)

In [33]:
df.head()

,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [34]:
df.isnull().sum()

loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [35]:
df.dropna(inplace=True)

In [36]:
df.head()

,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [37]:
df.isnull().sum()

loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [39]:
df.rename(columns={"loan_amnt":"Loan Amount",	"loan_intent":"Loan Intent","loan_int_rate":"Loan interest Rate","loan_percent_income":"Loan percentage","cb_person_cred_hist_length":"Credit History",	"credit_score":"Credit Score","previous_loan_defaults_on_file":"Previous Loan",	"loan_status":"Loan Status"},inplace=True)

In [40]:
df.head()

,Loan Amount,Loan Intent,Loan interest Rate,Loan percentage,Credit History,Credit Score,Previous Loan,Loan Status
0,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [45]:
df.dtypes

Loan Amount           float64
Loan Intent            object
Loan interest Rate    float64
Loan percentage       float64
Credit History        float64
Credit Score            int64
Previous Loan          object
Loan Status             int64
dtype: object

In [46]:
df['Credit History']=df['Credit History'].astype(int)

In [47]:
df['Credit History'].dtype

dtype('int64')

#Check Unique Values of All Columns.

In [48]:
df['Credit History'].unique()

array([ 3,  2,  4,  8,  7,  6,  9, 10,  5, 11, 16, 15, 12, 13, 17, 14, 25,
       28, 27, 22, 19, 29, 23, 26, 20, 21, 30, 24, 18])

In [42]:
df['Credit Score'].unique()

array([561, 504, 635, 675, 586, 532, 701, 585, 544, 640, 621, 651, 573,
       708, 583, 670, 663, 694, 709, 679, 684, 662, 691, 600, 654, 626,
       607, 700, 553, 589, 681, 567, 669, 606, 582, 649, 602, 616, 631,
       637, 695, 620, 622, 645, 624, 570, 648, 652, 559, 623, 609, 579,
       688, 661, 562, 664, 564, 598, 557, 677, 690, 599, 604, 601, 634,
       671, 789, 538, 587, 683, 518, 617, 668, 673, 706, 536, 689, 595,
       584, 642, 614, 597, 625, 603, 643, 508, 505, 593, 686, 646, 697,
       615, 687, 650, 588, 658, 531, 665, 703, 594, 618, 574, 577, 653,
       630, 660, 639, 612, 628, 592, 580, 678, 672, 613, 566, 718, 484,
       699, 656, 659, 636, 554, 807, 578, 674, 608, 569, 629, 560, 548,
       667, 676, 581, 655, 551, 529, 666, 576, 633, 611, 657, 647, 542,
       692, 545, 540, 525, 537, 641, 539, 563, 712, 491, 590, 572, 528,
       638, 627, 596, 547, 507, 565, 693, 522, 632, 556, 499, 704, 503,
       714, 552, 555, 558, 521, 605, 571, 591, 719, 610, 535, 644, 523,
       546, 702, 711, 534, 805, 682, 447, 725, 680, 568, 524, 710, 707,
       619, 460, 696, 527, 511, 477, 575, 496, 685, 476, 502, 541, 722,
       506, 487, 530, 515, 513, 520, 724, 514, 501, 549, 720, 486, 716,
       465, 509, 517, 444, 482, 698, 443, 512, 526, 454, 550, 462, 717,
       727, 715, 543, 448, 713, 721, 481, 723, 533, 705, 483, 740, 495,
       459, 489, 519, 494, 498, 488, 468, 490, 479, 510, 472, 480, 421,
       473, 500, 493, 441, 485, 450, 467, 461, 475, 463, 728, 735, 458,
       456, 726, 729, 750, 455, 478, 453, 445, 431, 737, 497, 492, 437,
       516, 451, 434, 435, 439, 466, 440, 449, 469, 471, 730, 470, 734,
       751, 739, 736, 738, 733, 732, 731, 741, 748, 744, 762, 742, 745,
       743, 464, 390, 755, 747, 759, 746, 756, 753, 764, 850, 760, 754,
       770, 784, 773, 765, 772, 419, 474, 430, 418, 420, 792, 768, 457,
       446, 767])

In [49]:
df['Loan Intent'].unique()

array(['PERSONAL', 'EDUCATION', 'MEDICAL', 'VENTURE', 'HOMEIMPROVEMENT',
       'DEBTCONSOLIDATION'], dtype=object)

In [50]:
df['Loan Amount'].unique()

array([35000.,  1000.,  5500., ..., 12229.,  2771.,  6665.])

In [51]:
df['Loan Status'].unique()

array([1, 0])

In [52]:
df['Loan percentage'].unique()

array([0.49, 0.08, 0.44, 0.53, 0.19, 0.37, 0.35, 0.13, 0.34, 0.3 , 0.27,
       0.25, 0.05, 0.24, 0.31, 0.26, 0.12, 0.18, 0.21, 0.43, 0.11, 0.4 ,
       0.32, 0.1 , 0.41, 0.22, 0.07, 0.02, 0.17, 0.51, 0.38, 0.33, 0.06,
       0.03, 0.28, 0.04, 0.09, 0.2 , 0.23, 0.15, 0.48, 0.5 , 0.14, 0.42,
       0.01, 0.46, 0.29, 0.39, 0.36, 0.16, 0.  , 0.57, 0.45, 0.52, 0.55,
       0.61, 0.62, 0.66, 0.54, 0.47, 0.56, 0.58, 0.63, 0.59])

In [54]:
df['Previous Loan'].unique()

array(['No', 'Yes'], dtype=object)

In [55]:
df['Loan interest Rate'].unique()

array([16.02, 11.14, 12.87, ..., 19.11, 19.8 , 16.92])